ktor:
    application:
        modules:
            - com.naveedkamran.examples.ApplicationKt.module
    deployment:
        port: 8080
ktor:
  kafka:
    schema.registry.url:
      - "SCHEMA_REGISTRY_URL"
    common:
      bootstrap.servers:
        - "BOOTSTRAP_SERVERS"
      # Additional attributes
    admin:
    # Additional attributes
    consumer:
      group.id: "my-group-id"
      # Additional attributes
    producer:
      client.id: "my-client-id"
      # Additional attributes
    topics:
      - name: my-topic
        partitions: 1
        configs:
          message.timestamp.type: CreateTime
          # Additional attributes
